name: on release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v2
        with:
          version: 7.14.2
      - run: pnpm i
      - run: pnpm build
      - uses: actions/upload-artifact@v3
        with:
          name: blob-to-url
          path: |
            ./
            !node_modules

  publish-npm-registry:
    needs: build
    runs-on: ubuntu-latest
    environment: npm package
    steps:
      - uses: actions/download-artifact@v4.1.7
        with:
          name: blob-to-url
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v2
        with:
          version: 7.14.2
        # --no-git-checks: 작업 과정 중 제외 및 추가되는 파일이 발생하여 생기는 문제 무시합니다.
      - uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
  # publish-github-registry:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     packages: write
  #     contents: read
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #         registry-url: https://npm.pkg.github.com/
  #         scope: "@devcomfort"
  #     - run: npm ci
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
